# Numpy: Numerical Python library
Numpy es la libreria base para realizar operaciones aritmeticas a escala con python, python suele ser un lenguaje "lento" comparado con leguajes compilados. Numpy nos ofrece bindings de python a C++ lo que implica tener acceso a la rapidez de C++ con el comfort de scripting de python.

# Instalacion de NumPy
```bash
pip install numpy
```

### 1.- Importando Numpy

In [ ]:
# Importando Numpy
import numpy as np

# Verificando version de np
print(np.__version__)

2.3.3


In [9]:
# Lista nativa de python
miLista = [1,2,3,4]

print(type(miLista))
print(f"Lista Base: {miLista}")



# Multiplicando por 2 a los elementos de la lista

print(f"Lista Multiplicada? {miLista*2}")

# Duplico la lista en vez de multiplicar por 2

for numero in miLista:
    miLista.remove(numero)
    miLista.append(numero*2)

# Multiplicando por 2 a los elementos de la lista

print(f"Lista Multiplicada con for: {miLista}")


<class 'list'>
Lista Base: [1, 2, 3, 4]
Lista Multiplicada? [1, 2, 3, 4, 1, 2, 3, 4]
Lista Multiplicada con for: [2, 6, 4, 8]


In [11]:
miNumpyArray = np.array([1,2,3,4])

print(type(miNumpyArray))
print(f"Array de numpy{miNumpyArray}")

# Multiplicando * 2

miNumpyArray = miNumpyArray * 2

print(f"Numpy Array multiplicado * 2: {miNumpyArray}")

<class 'numpy.ndarray'>
Array de numpy[1 2 3 4]
Numpy Array multiplicado * 2: [2 4 6 8]


### 2.-Arrays Multidimensionales

In [14]:
# Un solo dato
array = np.array('A')

print(f"dimensiones: {array.ndim}")

# Una lista de datos
array = np.array(['A','B','C'])

print(f"dimensiones: {array.ndim}")

# Una lista de listas
array = np.array([['A','B','C'],
                 ['D','E','F'],
                 ['G','H','I']])

print(f"dimensiones: {array.ndim}")

dimensiones: 0
dimensiones: 1
dimensiones: 2


In [20]:
# array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
#                  [['J','K','L'],['M','N','O'],['P','Q','R']],
#                   [['S','T','U'],['V','W','X'],['Y','Z']]])

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])


print(f"dimensiones: {array.ndim}")

profundidad, columnas, filas = array.shape

print(f"""Profundidad del array: {profundidad}
         Columnas del array: {columnas}
         Filas del array: {filas}         
      """)

dimensiones: 3
Profundidad del array: 3
         Columnas del array: 3
         Filas del array: 3         
      


### 3.-Accesando indices

In [28]:
# Indexacion por cadena - Chain Indexing - Python

print(array[0][0][0])

# Indexacion Multidimensional - Numpy

print(array[0,0,0])

for profundidad in range(3):
    for filas in range(3):
        for columnas in range(3):
            print(array[profundidad,filas,columnas])
            

A
A
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z



### 4.- Ejercicio ICI

In [27]:
# ejercicio ici
ici = array[0,2,2] + array[0,0,2] + array[0,2,2]
print(ici)

ICI


### 5.- Rellenando con ciertos valores matrices o arreglos de 2 dimensiones

In [29]:
# Arreglos con ceros, unos o valores constantes
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nFull con 7:\n", full)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full con 7:
 [[7 7 7]
 [7 7 7]]


### 6.- Rangos y secuencias

In [30]:
# Secuencias con np.arange y np.linspace
rango = np.arange(0, 10, 2)  # inicio, fin, paso
espaciado = np.linspace(0, 1, 5)  # inicio, fin, cantidad de puntos

print("arange:", rango)
print("linspace:", espaciado)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


### 7.-Atributos completos de una arreglo

In [32]:
# Arreglo bidimensional
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArreglo b:\n", b)

print("Forma (shape):", b.shape)
print("Dimensiones (ndim):", b.ndim)
print("Tamaño total (size):", b.size)
print("Tipo de dato (dtype):", b.dtype)


Arreglo b:
 [[1 2 3]
 [4 5 6]]
Forma (shape): (2, 3)
Dimensiones (ndim): 2
Tamaño total (size): 6
Tipo de dato (dtype): int64


### 8.- Slicing

In [33]:
# Slicing (porciones)
print("Primera fila:", b[0, :])
print("Primera columna:", b[:, 0])
print("Subarreglo 2x2:\n", b[:2, 1:3])

# Modificar valores
b[0, 0] = 99
print("b modificado:\n", b)

Primera fila: [1 2 3]
Primera columna: [1 4]
Subarreglo 2x2:
 [[2 3]
 [5 6]]
b modificado:
 [[99  2  3]
 [ 4  5  6]]


### 9.- Operaciones aritmeticas

In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Suma:", x + y)
print("Resta:", x - y)
print("Multiplicación elemento a elemento:", x * y)
print("División:", x / y)
print("Potencia:", x ** 2)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación elemento a elemento: [ 4 10 18]
División: [0.25 0.4  0.5 ]
Potencia: [1 4 9]


### 10.- Toolkit de Numpy

In [35]:
print("Seno:", np.sin(x))
print("Media:", np.mean(x))
print("Máximo:", np.max(x))
print("Mínimo:", np.min(x))
print("Suma total:", np.sum(x))

Seno: [0.84147098 0.90929743 0.14112001]
Media: 2.0
Máximo: 3
Mínimo: 1
Suma total: 6


### 11.- Operaciones de Matrices

In [36]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices (producto punto)
print("Producto punto:\n", np.dot(m1, m2))

# Transpuesta
print("Transpuesta:\n", m1.T)

# Inversa y determinante
print("Inversa:\n", np.linalg.inv(m1))
print("Determinante:", np.linalg.det(m1))

Producto punto:
 [[19 22]
 [43 50]]
Transpuesta:
 [[1 3]
 [2 4]]
Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinante: -2.0000000000000004


### 12.- Flatten y reshape de vectores

In [37]:
c = np.arange(12)
print("Original:", c)

c_reshape = c.reshape((3, 4))
print("\nReshape (3x4):\n", c_reshape)

c_flat = c_reshape.flatten()
print("\nFlatten (1D):", c_flat)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


### 13.- Operaciones booleana

In [38]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25

print("Máscara:", mask)
print("Elementos mayores que 25:", arr[mask])

Máscara: [False False  True  True  True]
Elementos mayores que 25: [30 40 50]


### 14.- Aleatoriedad

In [39]:
np.random.seed(0)  # Semilla para reproducibilidad

rand_array = np.random.rand(2, 3)  # [0,1)
rand_ints = np.random.randint(0, 10, size=(2, 3))

print("Random float:\n", rand_array)
print("\nRandom int:\n", rand_ints)

Random float:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

Random int:
 [[4 7 6]
 [8 8 1]]
